#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 44
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 10

enum {
  sym_symbol = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_LT = 8,
  anon_sym_GT = 9,
  sym_integer = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  anon_sym_fn = 13,
  anon_sym_let = 14,
  anon_sym_if = 15,
  sym_comment = 16,
  sym_program = 17,
  sym__crisp = 18,
  sym_sexpr = 19,
  sym__literal = 20,
  sym_boolean = 21,
  sym__special_form = 22,
  sym_fn = 23,
  sym_fn_parameters = 24,
  sym_let = 25,
  sym_let_bindings = 26,
  sym__binding = 27,
  sym_binding = 28,
  sym_if = 29,
  aux_sym_program_repeat1 = 30,
  aux_sym_fn_parameters_repeat1 = 31,
  aux_sym_let_bindings_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_fn] = "fn",
  [anon_sym_let] = "let",
  [anon_sym_if] = "if",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym__crisp] = "_crisp",
  [sym_sexpr] = "sexpr",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym__special_form] = "_special_form",
  [sym_fn] = "fn",
  [sym_fn_parameters] = "fn_parameters",
  [sym_let] = "let",
  [sym_let_bindings] = "let_bindings",
  [sym__binding] = "_binding",
  [sym_binding] = "binding",
  [sym_if] = "if",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_fn_parameters_repeat1] = "fn_parameters_repeat1",
  [aux_sym_let_bindings_repeat1] = "let_bindings_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_if] = anon_sym_if,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym__crisp] = sym__crisp,
  [sym_sexpr] = sym_sexpr,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym__special_form] = sym__special_form,
  [sym_fn] = sym_fn,
  [sym_fn_parameters] = sym_fn_parameters,
  [sym_let] = sym_let,
  [sym_let_bindings] = sym_let_bindings,
  [sym__binding] = sym__binding,
  [sym_binding] = sym_binding,
  [sym_if] = sym_if,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_fn_parameters_repeat1] = aux_sym_fn_parameters_repeat1,
  [aux_sym_let_bindings_repeat1] = aux_sym_let_bindings_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__crisp] = {
    .visible = false,
    .named = true,
  },
  [sym_sexpr] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__special_form] = {
    .visible = false,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_let_bindings] = {
    .visible = true,
    .named = true,
  },
  [sym__binding] = {
    .visible = false,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fn_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_let_bindings_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_binding = 2,
  field_bindings = 3,
  field_body = 4,
  field_false_branch = 5,
  field_function = 6,
  field_parameters = 7,
  field_predicate = 8,
  field_true_branch = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_binding] = "binding",
  [field_bindings] = "bindings",
  [field_body] = "body",
  [field_false_branch] = "false_branch",
  [field_function] = "function",
  [field_parameters] = "parameters",
  [field_predicate] = "predicate",
  [field_true_branch] = "true_branch",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 4},
  [7] = {.index = 12, .length = 2},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 1},
  [1] =
    {field_bindings, 2},
  [2] =
    {field_arguments, 2},
    {field_function, 1},
  [4] =
    {field_body, 3},
    {field_parameters, 2},
  [6] =
    {field_binding, 1, .inherited = true},
    {field_body, 1, .inherited = true},
  [8] =
    {field_binding, 0, .inherited = true},
    {field_binding, 1, .inherited = true},
    {field_body, 0, .inherited = true},
    {field_body, 1, .inherited = true},
  [12] =
    {field_bindings, 2},
    {field_body, 3},
  [14] =
    {field_false_branch, 4},
    {field_predicate, 2},
    {field_true_branch, 3},
  [17] =
    {field_binding, 1},
    {field_body, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '(') ADVANCE(3);
      if (lookahead == ')') ADVANCE(4);
      if (lookahead == ';') ADVANCE(1);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == ']') ADVANCE(6);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == ';') ADVANCE(13);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(92),
    [sym__crisp] = STATE(8),
    [sym_sexpr] = STATE(8),
    [sym__literal] = STATE(8),
    [sym_boolean] = STATE(8),
    [sym__special_form] = STATE(8),
    [sym_fn] = STATE(8),
    [sym_let] = STATE(8),
    [sym_if] = STATE(8),
    [aux_sym_program_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_symbol] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_symbol] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(24),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(30),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(36),
    [anon_sym_false] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__crisp] = STATE(7),
    [sym_sexpr] = STATE(7),
    [sym__literal] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym__special_form] = STATE(7),
    [sym_fn] = STATE(7),
    [sym_let] = STATE(7),
    [sym_if] = STATE(7),
    [sym_symbol] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(41),
    [anon_sym_let] = ACTIONS(43),
    [anon_sym_if] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym__crisp] = STATE(16),
    [sym_sexpr] = STATE(16),
    [sym__literal] = STATE(16),
    [sym_boolean] = STATE(16),
    [sym__special_form] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_let] = STATE(16),
    [sym_if] = STATE(16),
    [sym_symbol] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_let] = ACTIONS(51),
    [anon_sym_if] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym__crisp] = STATE(20),
    [sym_sexpr] = STATE(20),
    [sym__literal] = STATE(20),
    [sym_boolean] = STATE(20),
    [sym__special_form] = STATE(20),
    [sym_fn] = STATE(20),
    [sym_let] = STATE(20),
    [sym_if] = STATE(20),
    [sym_symbol] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(55),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(57),
    [anon_sym_let] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym__crisp] = STATE(12),
    [sym_sexpr] = STATE(12),
    [sym__literal] = STATE(12),
    [sym_boolean] = STATE(12),
    [sym__special_form] = STATE(12),
    [sym_fn] = STATE(12),
    [sym_let] = STATE(12),
    [sym_if] = STATE(12),
    [sym_symbol] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(63),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(65),
    [anon_sym_let] = ACTIONS(67),
    [anon_sym_if] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym__crisp] = STATE(22),
    [sym_sexpr] = STATE(22),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym__special_form] = STATE(22),
    [sym_fn] = STATE(22),
    [sym_let] = STATE(22),
    [sym_if] = STATE(22),
    [aux_sym_program_repeat1] = STATE(22),
    [sym_symbol] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [8] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(75),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [9] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [10] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [11] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(81),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [12] = {
    [sym__crisp] = STATE(11),
    [sym_sexpr] = STATE(11),
    [sym__literal] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym__special_form] = STATE(11),
    [sym_fn] = STATE(11),
    [sym_let] = STATE(11),
    [sym_if] = STATE(11),
    [aux_sym_program_repeat1] = STATE(11),
    [sym_symbol] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(73),
    [sym_integer] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [13] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(79),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [14] = {
    [sym__crisp] = STATE(13),
    [sym_sexpr] = STATE(13),
    [sym__literal] = STATE(13),
    [sym_boolean] = STATE(13),
    [sym__special_form] = STATE(13),
    [sym_fn] = STATE(13),
    [sym_let] = STATE(13),
    [sym_if] = STATE(13),
    [aux_sym_program_repeat1] = STATE(13),
    [sym_symbol] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(87),
    [sym_integer] = ACTIONS(85),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [15] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [16] = {
    [sym__crisp] = STATE(18),
    [sym_sexpr] = STATE(18),
    [sym__literal] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym__special_form] = STATE(18),
    [sym_fn] = STATE(18),
    [sym_let] = STATE(18),
    [sym_if] = STATE(18),
    [aux_sym_program_repeat1] = STATE(18),
    [sym_symbol] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(89),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [17] = {
    [sym__crisp] = STATE(19),
    [sym_sexpr] = STATE(19),
    [sym__literal] = STATE(19),
    [sym_boolean] = STATE(19),
    [sym__special_form] = STATE(19),
    [sym_fn] = STATE(19),
    [sym_let] = STATE(19),
    [sym_if] = STATE(19),
    [aux_sym_program_repeat1] = STATE(19),
    [sym_symbol] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(91),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [18] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [19] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [20] = {
    [sym__crisp] = STATE(15),
    [sym_sexpr] = STATE(15),
    [sym__literal] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym__special_form] = STATE(15),
    [sym_fn] = STATE(15),
    [sym_let] = STATE(15),
    [sym_if] = STATE(15),
    [aux_sym_program_repeat1] = STATE(15),
    [sym_symbol] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [21] = {
    [sym__crisp] = STATE(10),
    [sym_sexpr] = STATE(10),
    [sym__literal] = STATE(10),
    [sym_boolean] = STATE(10),
    [sym__special_form] = STATE(10),
    [sym_fn] = STATE(10),
    [sym_let] = STATE(10),
    [sym_if] = STATE(10),
    [aux_sym_program_repeat1] = STATE(10),
    [sym_symbol] = ACTIONS(95),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(95),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [22] = {
    [sym__crisp] = STATE(2),
    [sym_sexpr] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym__special_form] = STATE(2),
    [sym_fn] = STATE(2),
    [sym_let] = STATE(2),
    [sym_if] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [23] = {
    [sym__crisp] = STATE(9),
    [sym_sexpr] = STATE(9),
    [sym__literal] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym__special_form] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [aux_sym_program_repeat1] = STATE(9),
    [sym_symbol] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(97),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [24] = {
    [sym__crisp] = STATE(32),
    [sym_sexpr] = STATE(32),
    [sym__literal] = STATE(32),
    [sym_boolean] = STATE(32),
    [sym__special_form] = STATE(32),
    [sym_fn] = STATE(32),
    [sym_let] = STATE(32),
    [sym_if] = STATE(32),
    [sym_symbol] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(99),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [25] = {
    [sym__crisp] = STATE(101),
    [sym_sexpr] = STATE(101),
    [sym__literal] = STATE(101),
    [sym_boolean] = STATE(101),
    [sym__special_form] = STATE(101),
    [sym_fn] = STATE(101),
    [sym_let] = STATE(101),
    [sym_if] = STATE(101),
    [sym_symbol] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(101),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [26] = {
    [sym__crisp] = STATE(100),
    [sym_sexpr] = STATE(100),
    [sym__literal] = STATE(100),
    [sym_boolean] = STATE(100),
    [sym__special_form] = STATE(100),
    [sym_fn] = STATE(100),
    [sym_let] = STATE(100),
    [sym_if] = STATE(100),
    [sym_symbol] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(103),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [27] = {
    [sym__crisp] = STATE(99),
    [sym_sexpr] = STATE(99),
    [sym__literal] = STATE(99),
    [sym_boolean] = STATE(99),
    [sym__special_form] = STATE(99),
    [sym_fn] = STATE(99),
    [sym_let] = STATE(99),
    [sym_if] = STATE(99),
    [sym_symbol] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [28] = {
    [sym__crisp] = STATE(24),
    [sym_sexpr] = STATE(24),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(24),
    [sym__special_form] = STATE(24),
    [sym_fn] = STATE(24),
    [sym_let] = STATE(24),
    [sym_if] = STATE(24),
    [sym_symbol] = ACTIONS(107),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(107),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [29] = {
    [sym__crisp] = STATE(98),
    [sym_sexpr] = STATE(98),
    [sym__literal] = STATE(98),
    [sym_boolean] = STATE(98),
    [sym__special_form] = STATE(98),
    [sym_fn] = STATE(98),
    [sym_let] = STATE(98),
    [sym_if] = STATE(98),
    [sym_symbol] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(109),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [30] = {
    [sym__crisp] = STATE(97),
    [sym_sexpr] = STATE(97),
    [sym__literal] = STATE(97),
    [sym_boolean] = STATE(97),
    [sym__special_form] = STATE(97),
    [sym_fn] = STATE(97),
    [sym_let] = STATE(97),
    [sym_if] = STATE(97),
    [sym_symbol] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(111),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [31] = {
    [sym__crisp] = STATE(39),
    [sym_sexpr] = STATE(39),
    [sym__literal] = STATE(39),
    [sym_boolean] = STATE(39),
    [sym__special_form] = STATE(39),
    [sym_fn] = STATE(39),
    [sym_let] = STATE(39),
    [sym_if] = STATE(39),
    [sym_symbol] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(113),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [32] = {
    [sym__crisp] = STATE(96),
    [sym_sexpr] = STATE(96),
    [sym__literal] = STATE(96),
    [sym_boolean] = STATE(96),
    [sym__special_form] = STATE(96),
    [sym_fn] = STATE(96),
    [sym_let] = STATE(96),
    [sym_if] = STATE(96),
    [sym_symbol] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(115),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [33] = {
    [sym__crisp] = STATE(90),
    [sym_sexpr] = STATE(90),
    [sym__literal] = STATE(90),
    [sym_boolean] = STATE(90),
    [sym__special_form] = STATE(90),
    [sym_fn] = STATE(90),
    [sym_let] = STATE(90),
    [sym_if] = STATE(90),
    [sym_symbol] = ACTIONS(117),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(117),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [34] = {
    [sym__crisp] = STATE(95),
    [sym_sexpr] = STATE(95),
    [sym__literal] = STATE(95),
    [sym_boolean] = STATE(95),
    [sym__special_form] = STATE(95),
    [sym_fn] = STATE(95),
    [sym_let] = STATE(95),
    [sym_if] = STATE(95),
    [sym_symbol] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(119),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [35] = {
    [sym__crisp] = STATE(94),
    [sym_sexpr] = STATE(94),
    [sym__literal] = STATE(94),
    [sym_boolean] = STATE(94),
    [sym__special_form] = STATE(94),
    [sym_fn] = STATE(94),
    [sym_let] = STATE(94),
    [sym_if] = STATE(94),
    [sym_symbol] = ACTIONS(121),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(121),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [36] = {
    [sym__crisp] = STATE(93),
    [sym_sexpr] = STATE(93),
    [sym__literal] = STATE(93),
    [sym_boolean] = STATE(93),
    [sym__special_form] = STATE(93),
    [sym_fn] = STATE(93),
    [sym_let] = STATE(93),
    [sym_if] = STATE(93),
    [sym_symbol] = ACTIONS(123),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(123),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [37] = {
    [sym__crisp] = STATE(38),
    [sym_sexpr] = STATE(38),
    [sym__literal] = STATE(38),
    [sym_boolean] = STATE(38),
    [sym__special_form] = STATE(38),
    [sym_fn] = STATE(38),
    [sym_let] = STATE(38),
    [sym_if] = STATE(38),
    [sym_symbol] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(125),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [38] = {
    [sym__crisp] = STATE(36),
    [sym_sexpr] = STATE(36),
    [sym__literal] = STATE(36),
    [sym_boolean] = STATE(36),
    [sym__special_form] = STATE(36),
    [sym_fn] = STATE(36),
    [sym_let] = STATE(36),
    [sym_if] = STATE(36),
    [sym_symbol] = ACTIONS(127),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(127),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [39] = {
    [sym__crisp] = STATE(34),
    [sym_sexpr] = STATE(34),
    [sym__literal] = STATE(34),
    [sym_boolean] = STATE(34),
    [sym__special_form] = STATE(34),
    [sym_fn] = STATE(34),
    [sym_let] = STATE(34),
    [sym_if] = STATE(34),
    [sym_symbol] = ACTIONS(129),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(129),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [40] = {
    [sym__crisp] = STATE(91),
    [sym_sexpr] = STATE(91),
    [sym__literal] = STATE(91),
    [sym_boolean] = STATE(91),
    [sym__special_form] = STATE(91),
    [sym_fn] = STATE(91),
    [sym_let] = STATE(91),
    [sym_if] = STATE(91),
    [sym_symbol] = ACTIONS(131),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(131),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [41] = {
    [sym__crisp] = STATE(35),
    [sym_sexpr] = STATE(35),
    [sym__literal] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym__special_form] = STATE(35),
    [sym_fn] = STATE(35),
    [sym_let] = STATE(35),
    [sym_if] = STATE(35),
    [sym_symbol] = ACTIONS(133),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(133),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [42] = {
    [sym__crisp] = STATE(41),
    [sym_sexpr] = STATE(41),
    [sym__literal] = STATE(41),
    [sym_boolean] = STATE(41),
    [sym__special_form] = STATE(41),
    [sym_fn] = STATE(41),
    [sym_let] = STATE(41),
    [sym_if] = STATE(41),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(135),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [43] = {
    [sym__crisp] = STATE(102),
    [sym_sexpr] = STATE(102),
    [sym__literal] = STATE(102),
    [sym_boolean] = STATE(102),
    [sym__special_form] = STATE(102),
    [sym_fn] = STATE(102),
    [sym_let] = STATE(102),
    [sym_if] = STATE(102),
    [sym_symbol] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [sym_integer] = ACTIONS(137),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [21] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [42] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(147), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [63] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(151), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(155), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(159), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(163), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [147] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(169), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [167] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(173), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [187] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(177), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [207] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(173), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(173), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [247] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(173), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [267] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
    ACTIONS(184), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_LT,
    STATE(57), 1,
      aux_sym_let_bindings_repeat1,
    ACTIONS(182), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_symbol,
    STATE(58), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
    ACTIONS(196), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [310] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(200), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
  [340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 4,
      sym_symbol,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(206), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [356] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    STATE(65), 1,
      aux_sym_let_bindings_repeat1,
  [378] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    STATE(66), 1,
      aux_sym_let_bindings_repeat1,
  [400] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    STATE(67), 1,
      aux_sym_let_bindings_repeat1,
  [422] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_let_bindings_repeat1,
  [444] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_let_bindings_repeat1,
  [466] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_let_bindings_repeat1,
  [488] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    ACTIONS(224), 1,
      anon_sym_GT,
    STATE(57), 1,
      aux_sym_let_bindings_repeat1,
  [510] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      anon_sym_GT,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_LT,
    STATE(68), 1,
      aux_sym_let_bindings_repeat1,
  [532] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 1,
      anon_sym_LT,
    STATE(21), 1,
      sym_let_bindings,
  [551] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(236), 1,
      anon_sym_RBRACK,
    STATE(58), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [566] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_LT,
    STATE(25), 1,
      sym_fn_parameters,
  [585] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_LT,
    STATE(43), 1,
      sym_fn_parameters,
  [604] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 1,
      anon_sym_LT,
    STATE(23), 1,
      sym_let_bindings,
  [623] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_LT,
    STATE(33), 1,
      sym_fn_parameters,
  [642] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 1,
      anon_sym_LT,
    STATE(17), 1,
      sym_let_bindings,
  [661] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_LT,
    STATE(40), 1,
      sym_fn_parameters,
  [680] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(58), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [695] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(246), 1,
      anon_sym_GT,
    STATE(84), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [710] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(85), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(71), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [740] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(78), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [755] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 1,
      anon_sym_LT,
    STATE(14), 1,
      sym_let_bindings,
  [774] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(236), 1,
      anon_sym_GT,
    STATE(58), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [789] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(58), 3,
      sym__binding,
      sym_binding,
      aux_sym_fn_parameters_repeat1,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    STATE(27), 2,
      sym__binding,
      sym_binding,
  [815] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    STATE(29), 2,
      sym__binding,
      sym_binding,
  [826] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    STATE(30), 2,
      sym__binding,
      sym_binding,
  [837] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_symbol,
    STATE(26), 2,
      sym__binding,
      sym_binding,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
  [862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
  [876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RBRACK,
  [883] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
  [890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_GT,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RBRACK,
  [911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
  [918] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_GT,
  [925] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_GT,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(44)] = 0,
  [SMALL_STATE(45)] = 21,
  [SMALL_STATE(46)] = 42,
  [SMALL_STATE(47)] = 63,
  [SMALL_STATE(48)] = 84,
  [SMALL_STATE(49)] = 105,
  [SMALL_STATE(50)] = 126,
  [SMALL_STATE(51)] = 147,
  [SMALL_STATE(52)] = 167,
  [SMALL_STATE(53)] = 187,
  [SMALL_STATE(54)] = 207,
  [SMALL_STATE(55)] = 227,
  [SMALL_STATE(56)] = 247,
  [SMALL_STATE(57)] = 267,
  [SMALL_STATE(58)] = 292,
  [SMALL_STATE(59)] = 310,
  [SMALL_STATE(60)] = 326,
  [SMALL_STATE(61)] = 340,
  [SMALL_STATE(62)] = 356,
  [SMALL_STATE(63)] = 378,
  [SMALL_STATE(64)] = 400,
  [SMALL_STATE(65)] = 422,
  [SMALL_STATE(66)] = 444,
  [SMALL_STATE(67)] = 466,
  [SMALL_STATE(68)] = 488,
  [SMALL_STATE(69)] = 510,
  [SMALL_STATE(70)] = 532,
  [SMALL_STATE(71)] = 551,
  [SMALL_STATE(72)] = 566,
  [SMALL_STATE(73)] = 585,
  [SMALL_STATE(74)] = 604,
  [SMALL_STATE(75)] = 623,
  [SMALL_STATE(76)] = 642,
  [SMALL_STATE(77)] = 661,
  [SMALL_STATE(78)] = 680,
  [SMALL_STATE(79)] = 695,
  [SMALL_STATE(80)] = 710,
  [SMALL_STATE(81)] = 725,
  [SMALL_STATE(82)] = 740,
  [SMALL_STATE(83)] = 755,
  [SMALL_STATE(84)] = 774,
  [SMALL_STATE(85)] = 789,
  [SMALL_STATE(86)] = 804,
  [SMALL_STATE(87)] = 815,
  [SMALL_STATE(88)] = 826,
  [SMALL_STATE(89)] = 837,
  [SMALL_STATE(90)] = 848,
  [SMALL_STATE(91)] = 855,
  [SMALL_STATE(92)] = 862,
  [SMALL_STATE(93)] = 869,
  [SMALL_STATE(94)] = 876,
  [SMALL_STATE(95)] = 883,
  [SMALL_STATE(96)] = 890,
  [SMALL_STATE(97)] = 897,
  [SMALL_STATE(98)] = 904,
  [SMALL_STATE(99)] = 911,
  [SMALL_STATE(100)] = 918,
  [SMALL_STATE(101)] = 925,
  [SMALL_STATE(102)] = 932,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(5),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(6),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(45),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, .production_id = 4),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, .production_id = 4),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr, 3, .production_id = 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexpr, 3, .production_id = 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 6, .production_id = 8),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 6, .production_id = 8),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5, .production_id = 7),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 5, .production_id = 7),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 4, .production_id = 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 4, .production_id = 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr, 4, .production_id = 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexpr, 4, .production_id = 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_bindings, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_bindings, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_bindings, 3, .production_id = 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_bindings, 3, .production_id = 5),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 1),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_bindings_repeat1, 2, .production_id = 6), SHIFT_REPEAT(88),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_bindings_repeat1, 2, .production_id = 6),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_bindings_repeat1, 2, .production_id = 6), SHIFT_REPEAT(87),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_bindings_repeat1, 2, .production_id = 6), SHIFT_REPEAT(86),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_bindings_repeat1, 2, .production_id = 6), SHIFT_REPEAT(89),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fn_parameters_repeat1, 2), SHIFT_REPEAT(53),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_parameters_repeat1, 2),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_parameters, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_parameters, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_bindings_repeat1, 4, .production_id = 9),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_parameters, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_parameters, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_crisp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
